spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   #swagger3和knife4j3需要加这个,否则报错
  #datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-q8gh40uo.sql.tencentcdb.com:29119/spring_security?useSSL=false
    username: root
    password: Aa@111111
  #jpa和datasource同级
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false   # 默认为true
    properties:
      hibernate:
        show_sql: true    #输出sql语句
        format_sql: true  #格式化输出的sql，否则会一行显示
  #redis
  redis:
    host: 43.143.216.21
    port: 6379
    database: 0
    timeout: 1800000
    password: Aa@111111
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲